#!/bin/bash

echo "Enter a character: "
read value

case $value in
[A-Z] )
    echo "Capital."
    ;;
[a-z] )
    echo "Small."
    ;;
[0-9] )
    echo "Number"
    ;;
* )
    echo "Invalid Input"
    ;;
esac
